server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSynchEmpty: 0
